name: 'Build images by buildx and push them to docker hub'
description: 'Supports custom Dockerfile name, tags, build context, etc.'
inputs:
  username:
    description: 'Username of docker hub'
    required: true
  token:
    description: 'Token to push Docker image to docker hub'
    required: true
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: "latest"
    required: false
  dockerfile:
    description: 'Dockerfile name'
    default: "Dockerfile"
    required: false
  build-context:
    description: 'Path to build context'
    default: "."
    required: false
  build-platform:
    description: 'Target build platforms'
    default: "linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v8"
    required: false
runs:
  using: "composite"
  steps:
    - name: REPOSITORY
      id: repository
      run: |
        IMAGE=$(echo docker.io/${{ inputs.username }}/${{ inputs.image-name }} | tr '[:upper:]' '[:lower:]')
        TAG=$(echo ${{ inputs.image-tag }} | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=image::$IMAGE"
        echo "::set-output name=tag::$TAG"
      shell: bash

    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1.2.0
    
    - name: Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Docker metadata
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ steps.repository.outputs.image }}
        labels: |
          org.opencontainers.image.version=${{ steps.repository.outputs.tag }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.title=${{ steps.repository.outputs.image }}
          
    - name: Docker login
      uses: docker/login-action@v1.12.0
      with:
        registry: docker.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        file: ${{ inputs.dockerfile }}
        push: true
        context: ${{ inputs.build-context }}
        platforms: ${{ inputs.build-platform }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        tags: |
          ${{ steps.repository.outputs.image }}:${{ steps.repository.outputs.tag }}
          ${{ steps.repository.outputs.image }}:latest